version: '2'

services:
  # Elasticsearch service
  es:
    image: elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    restart: "no"
